{{ config(
    materialized='table',
    tags=['activities_distribution', 'prod', 'salesforce']
) }}

select distinct
    a.annual_year,
    a.month,
    a.monthnum,
    a.quarter,
    a.state,
    a.district,
    a.block,
    a.other_block,
    a.village,
    a.other_village,
    a.account_name,
    a.account_type,
    a.type_of_initiative as activity_type_of_initiative,
    a.created_by,
    a.created_date,
    a.activity_name,
    activity_type,
    activity_category,
    activity_sub_type,
    other_sub_type,
    activity_start_date,
    activity_end_date,
    a.activity_id,
    objective_of_cfw_work,
    other_objective,
    is_education_and_health,
    number_of_activities,
    num_working_days,
    num_cfw_female,
    num_cfw_male,
    num_cfw_others,
    measurement_type,
    length,
    breadth,
    numbers,
    diameter,
    depth_height,
    actvity_conducted_with_students,
    num_s2s_participants,
    num_s2s_days,
    num_njpc_days,
    num_njpc_female,
    num_njpc_male,
    num_njpc_others,
    distribution_id,
    distribution_name,
    distribution_date,
    d.disaster_type,
    d.type_of_initiative as distribution_type_of_initiative,
    d.distribution_line_name,
    --dispatches.dispatch_name,
    --dispatches.dispatch_id,
    --dispatches.dispatch_date,
    --dispatches.dispatch_line_item_id,
    --dispatches.dispatch_line_item_name,
    d.implementation_inventory_name,
    d.source_of_material,
    d.bill_name,
    d.kit_type,
    d.sub_type,
    d.material_type,
    d.material_sub_category,
    d.other_material_name,
    d.purchase_kit_id,
    d.quantity,
    d.created_by as distribution_created_by,
    d.created_date as distribution_created_date
from 
{{ ref('int_activities') }} a 
LEFT JOIN {{ref('int_distributions')}} d 
    ON  a.activity_id=d.activity_id
--LEFT JOIN{{ ref('int_dispatches') }} dispatches 
--on d.dispatch_line_item_id = dispatches.dispatch_line_item_id

