{{ config(
    materialized='table',
    tags=['dispatch_status', 'staging', 'salesforce']
) }}

SELECT
    "Id" as dispatch_id,
    "Name",
    "POC__c" AS poc_id,
    "OwnerId",
    "Rate__c" AS rate,
    "Block__c" AS block,
    "Demand__c" AS demand_id,
    "IsDeleted",
    "Account__c" AS account_id,
    "Contact__c" AS contact_id,
    "Remarks__c" AS remarks,
    "CreatedById",
    "CreatedDate",
    "Driver_name__c" AS driver_name,
    "LastViewedDate",
    "SystemModstamp",
    "Transporter__c" AS transporter,
    "Goonj_office__c" AS goonj_office,
    "Local_Demand__c" AS local_demand,
    "Disaster_Type__c" AS disaster_type,
    "Dispatch_City__c" AS dispatch_city,
    "Dispatch_Date__c" AS dispatch_date,
    "LastActivityDate",
    "LastModifiedById",
    "LastModifiedDate",
    "Dispatch_State__c" AS dispatch_state,
    "Vehicle_Number__c" AS vehicle_number,
    "Dispatch_Street__c" AS dispatch_street,
    "Internal_Demand__c" AS internal_demand,
    "LastReferencedDate",
    "Name_of_the_POC__c" AS name_of_poc,
    "Dispatch_Address__c" AS dispatch_address_id,
    "Dispatch_Country__c" AS dispatch_country,
    "Dispatch_Pincode__c" AS dispatch_pincode,
    "E_Waybill_Number__c" AS e_waybill_number,
    "Contact_no_of_POC__c" AS contact_no_of_poc,
    "Dispatch_District__c" AS dispatch_district,
    "Dispatch_Entered_by__c" AS dispatch_entered_by,
    "POC_Contact_Details__c" AS poc_contact_details,
    "Driver_Contact_Number__c" AS driver_contact_number,
    "Demand_Post_Validation__c" AS demand_post_validation_id,
    "Truck_Vehicle_Capacity__c" AS truck_vehicle_capacity,
    "Total_No_Of_Bags_Packages__c" AS total_no_of_bags_packages,
    "Payments_Updates_With_Date__c" AS payments_updates_with_date,
    "Transporter_Consignment_No__c" AS transporter_consignment_no,
    "From_which_Processing_Center__c" AS from_which_processing_center,
    "Loading_and_Truck_Images_Link__c" AS loading_and_truck_images_link
FROM {{ source('staging_salesforce', 'dispatch_status') }}